[workspace]
members = ["bits-op", "example", "rayon-test", "struct-opt"]
resolver = "2"

[workspace.dependencies]
bit-struct = "0.3.2"
anyhow = "1.0.87"
structopt = "0.3.26"
rand = "0.8.5"
rayon = "1.10.0"
