[package]
name = "crate-example"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = { workspace = true }
parquet = { workspace = true }
serde_json = { workspace = true }
bon = { workspace = true }
tokio = { workspace = true }
tokio-stream = { workspace = true }
